INSERT INTO ai_brains (company_id, brain_key, name, mission, status, primary_metric, channels_json, actions_json, signals_json, examples_json, connectors_json, sort_order) VALUES
(1, 'commercial', 'Cerebro Comercial', 'Vender mas, recuperar oportunidades y responder conversaciones comerciales con aprobacion cuando corresponda.', 'active', 'Ventas recuperadas',
JSON_ARRAY('WhatsApp','Instagram','Messenger','Correo','CRM','Cotizaciones'),
JSON_ARRAY('Responder mensajes','Crear cotizaciones','Hacer seguimiento','Detectar clientes frios','Recuperar ventas','Agendar reuniones','Recomendar productos'),
JSON_ARRAY('Clientes que pidieron informacion y no compraron','Cotizaciones por vencer','Carritos abandonados','Mensajes sin respuesta'),
JSON_ARRAY('Hay 8 clientes que pidieron informacion y nunca compraron.','Recomiendo ofrecer el producto X al cliente Y por historial de compra.'),
JSON_ARRAY('whatsapp_business','instagram','facebook','gmail','outlook'), 1),
(1, 'administrative', 'Cerebro Administrativo', 'Ahorrar tiempo organizando correos, agenda, tareas, pagos, documentos y busqueda interna.', 'active', 'Horas ahorradas',
JSON_ARRAY('Correo','Calendario','Documentos','Tareas','Pagos'),
JSON_ARRAY('Revisar correos','Organizar agenda','Crear tareas','Recordar pagos','Reordenar documentos','Buscar contratos','Generar informes'),
JSON_ARRAY('Pagos por vencer','Reuniones sin preparacion','Contratos solicitados','Correos acumulados'),
JSON_ARRAY('Tienes 4 pagos pendientes esta semana.','Encontre el contrato marco solicitado en documentos legales.'),
JSON_ARRAY('gmail','outlook','google_calendar','documents'), 2),
(1, 'analytical', 'Cerebro Analitico', 'Analizar datos de ventas, gastos, inventario, CRM, Excel, CSV y bases de datos para encontrar causas y oportunidades.', 'active', 'Insights accionables',
JSON_ARRAY('Excel','CSV','Base de datos','Ventas','Gastos','Inventario','CRM'),
JSON_ARRAY('Comparar periodos','Detectar anomalias','Analizar margenes','Segmentar clientes','Crear reportes','Recomendar decisiones'),
JSON_ARRAY('Ventas bajaron 18%','Clientes del sur compran 40% mas','Producto con perdida','Inventario detenido'),
JSON_ARRAY('Las ventas bajaron un 18% respecto al mes pasado.','Este producto genera mas perdidas por descuentos y devoluciones.'),
JSON_ARRAY('spreadsheets','database','crm','reports'), 3),
(1, 'operational', 'Cerebro Operacional', 'Conectar plataformas operativas como Tilo u Obra OK para ejecutar pedidos, despachos, promociones, obras y compras.', 'sandbox', 'Procesos resueltos',
JSON_ARRAY('Tilo','Obra OK','Pedidos','Despachos','Promociones','Ordenes de compra'),
JSON_ARRAY('Confirmar despachos','Responder pedidos nuevos','Detectar carritos abandonados','Monitorear avance de obras','Alertar sobre costos','Avisar falta de materiales'),
JSON_ARRAY('Pedido nuevo','Carrito abandonado','Obra al 62%','Presupuesto superado','3 ordenes pendientes'),
JSON_ARRAY('Llego un pedido nuevo: confirma despacho.','La obra lleva 62% de avance y el presupuesto supero el costo esperado.'),
JSON_ARRAY('tilo','obra_ok','whatsapp_business','inventory'), 4),
(1, 'executive', 'Cerebro Ejecutivo', 'Actuar como gerente diario: resumir negocio, priorizar riesgos, recomendar llamadas y mostrar decisiones clave.', 'active', 'Decisiones priorizadas',
JSON_ARRAY('Dashboard','Reportes','CRM','Ventas','Operaciones','Finanzas'),
JSON_ARRAY('Crear resumen diario','Priorizar clientes','Detectar riesgos','Recomendar acciones','Comparar margen','Alertar vencimientos'),
JSON_ARRAY('Ventas del dia','Mensajes respondidos','Ventas cerradas','Clientes esperando','Cotizaciones por vencer','Margen bajo'),
JSON_ARRAY('Buenos dias, vendiste 2.8 millones y cerraste 14 ventas.','Recomiendo llamar a Constructora X hoy.'),
JSON_ARRAY('dashboard','crm','reports','ai_usage_logs'), 5);
