INSERT IGNORE INTO social_templates
  (company_id, industry, name, channel, objective, content_pillar, caption_pattern, hashtag_pattern, image_pattern, cta_pattern)
VALUES
(NULL, 'Retail / Ecommerce', 'Producto con margen alto', 'Instagram', 'Vender por WhatsApp', 'Producto rentable', 'Hoy conviene destacar {product} porque combina disponibilidad, buen margen y compra rapida. {brief}', '#promo #whatsapp #{product_slug} #ventas', 'Carrusel con producto, beneficio, precio referencial y sello de disponibilidad.', 'Escribenos por WhatsApp y te enviamos opciones'),
(NULL, 'Retail / Ecommerce', 'Recuperacion de carrito', 'WhatsApp', 'Cerrar pedidos', 'Recuperacion', 'Hola, vimos que consultaste por {product}. Tenemos stock y podemos ayudarte a cerrar tu pedido hoy.', '#whatsapp #pedido #{product_slug}', 'Imagen simple con producto y beneficio principal.', 'Responder "Quiero comprar"'),
(NULL, 'Construccion', 'Avance y confianza', 'LinkedIn', 'Generar confianza', 'Prueba social', 'En proyectos de construccion, {product} ayuda a reducir tiempos y ordenar compras. {brief}', '#construccion #gestion #{product_slug}', 'Grafica sobria con dato de avance, ahorro o control operativo.', 'Agenda una reunion comercial'),
(NULL, 'Construccion', 'Material pendiente', 'Facebook', 'Generar demanda', 'Urgencia operativa', 'Si tu obra necesita resolver materiales pendientes, {product} puede acelerar la compra y despacho.', '#obra #materiales #despacho', 'Foto del producto en contexto de obra con llamada de disponibilidad.', 'Cotiza por WhatsApp'),
(NULL, 'Servicios profesionales', 'Caso de uso', 'LinkedIn', 'Generar confianza', 'Autoridad', 'Caso practico: {product} permite ahorrar tiempo, ordenar seguimiento y mejorar conversion comercial. {brief}', '#servicios #crm #automatizacion', 'Grafica con antes/despues y metrica de ahorro o ventas.', 'Solicita una demo'),
(NULL, 'Servicios profesionales', 'Oferta de agenda', 'Instagram', 'Capturar leads', 'Agenda', 'Esta semana abrimos cupos para revisar tu proceso comercial con {product}.', '#agenda #ventas #{product_slug}', 'Imagen editorial limpia con beneficio y cupos disponibles.', 'Reserva por WhatsApp');
