<?php

use App\Controllers\AdminController;
use App\Controllers\ActionController;
use App\Controllers\ApiController;
use App\Controllers\AssistantController;
use App\Controllers\AssistantWorkspaceController;
use App\Controllers\AuthController;
use App\Controllers\BrainController;
use App\Controllers\BillingController;
use App\Controllers\ChatController;
use App\Controllers\CompanyController;
use App\Controllers\ControlController;
use App\Controllers\CrmController;
use App\Controllers\DashboardController;
use App\Controllers\DocumentController;
use App\Controllers\HomeController;
use App\Controllers\IntegrationController;
use App\Controllers\IntelligenceController;
use App\Controllers\InboxController;
use App\Controllers\KnowledgeController;
use App\Controllers\MvpController;
use App\Controllers\QuoteController;
use App\Controllers\SocialController;
use App\Controllers\SuperadminController;
use App\Controllers\WebhookController;

$router->get('/', [DashboardController::class, 'index']);
$router->get('/login', [AuthController::class, 'login']);
$router->post('/login', [AuthController::class, 'authenticate']);
$router->get('/register', [AuthController::class, 'register']);
$router->post('/register', [AuthController::class, 'store']);
$router->get('/forgot-password', [AuthController::class, 'forgot']);
$router->post('/forgot-password', [AuthController::class, 'sendReset']);
$router->get('/reset-password', [AuthController::class, 'reset']);
$router->post('/reset-password', [AuthController::class, 'updatePassword']);
$router->post('/logout', [AuthController::class, 'logout']);

$router->get('/dashboard', [DashboardController::class, 'index']);
$router->get('/my-day', [HomeController::class, 'myDay']);
$router->get('/workbench', [HomeController::class, 'workbench']);
$router->post('/workbench/task-done', [HomeController::class, 'completeWorkbenchTask']);
$router->get('/notifications', [HomeController::class, 'notifications']);
$router->get('/mvp', [MvpController::class, 'index']);
$router->get('/actions', [ActionController::class, 'index']);
$router->post('/actions/approve', [ActionController::class, 'approve']);
$router->post('/actions/reject', [ActionController::class, 'reject']);
$router->post('/actions/execute', [ActionController::class, 'execute']);
$router->post('/actions/fail', [ActionController::class, 'fail']);
$router->post('/actions/retry', [ActionController::class, 'retry']);
$router->post('/actions/comment', [ActionController::class, 'comment']);
$router->get('/controls', [ControlController::class, 'index']);
$router->post('/controls', [ControlController::class, 'store']);
$router->post('/controls/entry', [ControlController::class, 'addEntry']);
$router->post('/controls/status', [ControlController::class, 'transition']);
$router->post('/controls/alert', [ControlController::class, 'resolveAlert']);
$router->get('/brains', [BrainController::class, 'index']);
$router->get('/inbox', [InboxController::class, 'index']);
$router->post('/inbox/suggest', [InboxController::class, 'suggest']);
$router->post('/inbox/draft', [InboxController::class, 'saveDraft']);
$router->post('/inbox/send-draft', [InboxController::class, 'sendDraft']);
$router->post('/inbox/assign-human', [InboxController::class, 'assignHuman']);
$router->post('/inbox/status', [InboxController::class, 'status']);
$router->get('/chat', [ChatController::class, 'index']);
$router->post('/chat', [ChatController::class, 'ask']);
$router->get('/tasks', [AssistantWorkspaceController::class, 'tasks']);
$router->post('/tasks/update', [AssistantWorkspaceController::class, 'updateTask']);
$router->post('/tasks/comment', [AssistantWorkspaceController::class, 'addTaskComment']);
$router->post('/tasks/request-update', [AssistantWorkspaceController::class, 'requestTaskUpdate']);
$router->get('/automations', [AssistantWorkspaceController::class, 'automations']);
$router->get('/assistant', [AssistantController::class, 'edit']);
$router->post('/assistant', [AssistantController::class, 'update']);
$router->get('/documents', [DocumentController::class, 'index']);
$router->post('/documents', [DocumentController::class, 'upload']);
$router->get('/reports', [IntelligenceController::class, 'reports']);
$router->get('/analytics', [IntelligenceController::class, 'analytics']);
$router->get('/dashboards', [IntelligenceController::class, 'dashboards']);
$router->get('/intelligence-documents', [IntelligenceController::class, 'intelligenceDocuments']);
$router->get('/excel', [IntelligenceController::class, 'excel']);
$router->get('/indicators', [IntelligenceController::class, 'indicators']);
$router->get('/kpis', [IntelligenceController::class, 'kpis']);
$router->get('/knowledge-base', [KnowledgeController::class, 'base']);
$router->get('/catalogs', [KnowledgeController::class, 'catalogs']);
$router->get('/manuals', [KnowledgeController::class, 'manuals']);
$router->get('/training', [KnowledgeController::class, 'training']);
$router->get('/crm', [CrmController::class, 'index']);
$router->post('/crm', [CrmController::class, 'store']);
$router->post('/crm/note', [CrmController::class, 'addNote']);
$router->post('/crm/task', [CrmController::class, 'addTask']);
$router->post('/crm/task/complete', [CrmController::class, 'completeTask']);
$router->post('/crm/state', [CrmController::class, 'updateState']);
$router->post('/crm/opportunity', [CrmController::class, 'addOpportunity']);
$router->post('/crm/followups', [CrmController::class, 'automaticFollowups']);
$router->get('/quotes', [QuoteController::class, 'index']);
$router->post('/quotes', [QuoteController::class, 'store']);
$router->post('/quotes/product', [QuoteController::class, 'product']);
$router->get('/quotes/pdf', [QuoteController::class, 'pdf']);
$router->post('/quotes/send', [QuoteController::class, 'send']);
$router->post('/quotes/status', [QuoteController::class, 'status']);
$router->get('/social', [SocialController::class, 'index']);
$router->post('/social/generate', [SocialController::class, 'generate']);
$router->post('/social/status', [SocialController::class, 'status']);
$router->get('/integrations', [IntegrationController::class, 'index']);
$router->post('/integrations/ai', [IntegrationController::class, 'saveAi']);
$router->post('/integrations/ai/test', [IntegrationController::class, 'testAi']);
$router->get('/integrations/accounts', [IntegrationController::class, 'accounts']);
$router->post('/integrations/accounts', [IntegrationController::class, 'saveAccount']);
$router->post('/integrations/accounts/update', [IntegrationController::class, 'updateAccount']);
$router->get('/apis', [ApiController::class, 'index']);
$router->get('/company', [CompanyController::class, 'profile']);
$router->get('/users', [CompanyController::class, 'users']);
$router->post('/users', [CompanyController::class, 'storeUser']);
$router->post('/users/delete', [CompanyController::class, 'deleteUser']);
$router->get('/roles', [CompanyController::class, 'roles']);
$router->get('/company-settings', [CompanyController::class, 'settings']);
$router->get('/billing', [BillingController::class, 'index']);
$router->post('/billing/plan', [BillingController::class, 'changePlan']);
$router->get('/admin', [AdminController::class, 'index']);
$router->get('/admin/companies', [SuperadminController::class, 'companies']);
$router->post('/admin/companies', [SuperadminController::class, 'storeCompany']);
$router->get('/admin/plans', [SuperadminController::class, 'plans']);
$router->get('/admin/ai-tokens', [SuperadminController::class, 'aiTokens']);
$router->post('/admin/ai-tokens/openai-key', [SuperadminController::class, 'saveOpenAiKey']);
$router->post('/admin/ai-tokens/openai-key/delete', [SuperadminController::class, 'deleteOpenAiKey']);
$router->get('/admin/audit-logs', [SuperadminController::class, 'auditLogs']);
$router->get('/admin/system-status', [SuperadminController::class, 'systemStatus']);
$router->post('/webhooks/omnichannel', [WebhookController::class, 'omnichannel']);
