<?php
$bookingSuccess = $_SESSION['booking_success'] ?? null;
$bookingError = $_SESSION['booking_error'] ?? null;
unset($_SESSION['booking_success'], $_SESSION['booking_error']);
$spaceData = $space ?? null;
?>
<!doctype html>
<html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><title><?= e($spaceData['settings']['public_title'] ?? 'Reservas no disponibles') ?></title><link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Plus+Jakarta+Sans:wght@600;700;800&display=swap" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"><link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.css" rel="stylesheet"><link rel="stylesheet" href="<?= url('/assets/css/app.css') ?>"><link rel="stylesheet" href="<?= url('/assets/css/theme.css') ?>"></head>
<body class="booking-public-body"><main class="booking-public-wrap">
<?php if (!$spaceData): ?>
    <section class="booking-public-card empty-state"><span class="public-brand"><i class="bi bi-calendar-x"></i>AsisFly</span><h1>Esta agenda no está disponible</h1><p>El enlace puede haber vencido o la empresa pausó temporalmente sus reservas.</p></section>
<?php else: ?>
    <?php $settings = $spaceData['settings']; ?>
    <section class="booking-public-head"><span class="public-brand"><i class="bi bi-calendar-heart"></i><?= e($settings['company_name']) ?></span><h1><?= e($settings['public_title']) ?></h1><p><?= e($settings['public_description'] ?: 'Elige una hora disponible y completa tus datos.') ?></p><small><i class="bi bi-clock"></i> Horario local: <?= e($settings['timezone']) ?></small></section>
    <?php if ($bookingSuccess): ?><div class="alert alert-success booking-public-alert"><i class="bi bi-check2-circle"></i><?= e($bookingSuccess) ?></div><?php endif; ?>
    <?php if ($bookingError): ?><div class="alert alert-danger booking-public-alert"><i class="bi bi-exclamation-circle"></i><?= e($bookingError) ?></div><?php endif; ?>
    <section class="booking-public-card">
        <form method="get" action="<?= url('/reserve') ?>" class="booking-public-picker"><input type="hidden" name="space" value="<?= e((string) $settings['public_token']) ?>"><label>¿Con quién deseas reservar?</label><select class="form-select" name="resource_id" onchange="this.form.submit()"><?php foreach ($spaceData['resources'] as $resource): ?><option value="<?= e((string) $resource['id']) ?>" <?= (int) $resource['id'] === (int) $spaceData['selectedResourceId'] ? 'selected' : '' ?>><?= e($resource['name']) ?></option><?php endforeach; ?></select><div class="booking-public-days"><?php foreach ($spaceData['days'] as $day): ?><button type="submit" name="date" value="<?= e($day['date']) ?>" class="<?= $spaceData['selectedDate'] === $day['date'] ? 'active' : '' ?>"><small><?= e($day['day']) ?></small><strong><?= e($day['number']) ?></strong><span><?= e($day['month']) ?></span></button><?php endforeach; ?></div></form>
        <div class="booking-slots"><h2>Horas disponibles</h2><?php if ($spaceData['slots']): ?><div><?php foreach ($spaceData['slots'] as $slot): ?><button type="button" class="booking-slot" data-slot="<?= e($slot) ?>"><?= e($slot) ?></button><?php endforeach; ?></div><?php else: ?><p>No hay horas disponibles este día. Elige otra fecha.</p><?php endif; ?></div>
        <form class="booking-public-form" method="post" action="<?= url('/reserve') ?>" id="bookingForm"><?= csrf_field() ?><input type="hidden" name="space" value="<?= e((string) $settings['public_token']) ?>"><input type="hidden" name="resource_id" value="<?= e((string) $spaceData['selectedResourceId']) ?>"><input type="hidden" name="date" value="<?= e((string) $spaceData['selectedDate']) ?>"><input type="hidden" name="slot" id="bookingSlot" required><p id="selectedSlotMessage">Selecciona una hora para continuar.</p><input class="form-control" name="customer_name" placeholder="Tu nombre" required><div class="form-grid"><input class="form-control" name="customer_phone" placeholder="WhatsApp o teléfono"><input class="form-control" name="customer_email" type="email" placeholder="Correo (opcional)"></div><input class="form-control" name="service_name" placeholder="Motivo de la reserva (opcional)"><textarea class="form-control" name="notes" rows="2" placeholder="¿Hay algo que debamos saber?"></textarea><button class="btn btn-primary" type="submit" <?= !$spaceData['slots'] ? 'disabled' : '' ?>>Solicitar reserva<i class="bi bi-arrow-right"></i></button></form>
    </section>
<?php endif; ?>
</main><script>document.querySelectorAll('.booking-slot').forEach(function(button){button.addEventListener('click',function(){document.querySelectorAll('.booking-slot').forEach(function(item){item.classList.remove('active')});button.classList.add('active');document.getElementById('bookingSlot').value=button.dataset.slot;document.getElementById('selectedSlotMessage').textContent='Hora seleccionada: '+button.dataset.slot;});});</script></body></html>
