CREATE TABLE IF NOT EXISTS action_center_items (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  requested_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  title VARCHAR(180) NOT NULL,
  description TEXT NOT NULL,
  module VARCHAR(80) NOT NULL,
  brain VARCHAR(120) NOT NULL,
  action_type VARCHAR(80) NOT NULL,
  status ENUM('pending','approved','rejected','executed','failed') NOT NULL DEFAULT 'pending',
  priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  risk_level ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
  requires_approval BOOLEAN NOT NULL DEFAULT TRUE,
  payload_json JSON NULL,
  executed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_action_center_company FOREIGN KEY (company_id) REFERENCES companies(id),
  CONSTRAINT fk_action_center_requested_by FOREIGN KEY (requested_by) REFERENCES users(id),
  CONSTRAINT fk_action_center_approved_by FOREIGN KEY (approved_by) REFERENCES users(id),
  INDEX idx_action_center_company_status (company_id, status),
  INDEX idx_action_center_company_module (company_id, module)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
