CREATE TABLE IF NOT EXISTS ai_company_profiles (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL UNIQUE,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  company_name VARCHAR(180) NULL,
  description TEXT NULL,
  industry VARCHAR(160) NULL,
  main_offering TEXT NULL,
  customer_type TEXT NULL,
  value_proposition TEXT NULL,
  differentiators TEXT NULL,
  business_hours VARCHAR(220) NULL,
  locations TEXT NULL,
  website VARCHAR(220) NULL,
  contact_details TEXT NULL,
  primary_objective VARCHAR(220) NULL,
  published_at TIMESTAMP NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_profiles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_profiles_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_profiles_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_profiles_status (company_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_onboarding_sessions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  current_step VARCHAR(80) NOT NULL DEFAULT 'welcome',
  progress_percent TINYINT UNSIGNED NOT NULL DEFAULT 0,
  summary TEXT NULL,
  activated_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_onboarding_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_onboarding_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_onboarding_company_status (company_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_onboarding_answers (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  session_id BIGINT UNSIGNED NOT NULL,
  question_key VARCHAR(100) NOT NULL,
  question_label VARCHAR(220) NOT NULL,
  answer TEXT NULL,
  is_optional BOOLEAN NOT NULL DEFAULT FALSE,
  answered_by BIGINT UNSIGNED NULL,
  answered_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_answers_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_answers_session FOREIGN KEY (session_id) REFERENCES ai_onboarding_sessions(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_answers_user FOREIGN KEY (answered_by) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_ai_answer_session_question (session_id, question_key),
  INDEX idx_ai_answers_company (company_id, question_key)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_personalities (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL UNIQUE,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  tone ENUM('formal','professional','close','technical','commercial') NOT NULL DEFAULT 'professional',
  allow_emojis BOOLEAN NOT NULL DEFAULT FALSE,
  response_length ENUM('short','medium','detailed') NOT NULL DEFAULT 'medium',
  greeting_style VARCHAR(180) NULL,
  closing_style VARCHAR(180) NULL,
  use_customer_name BOOLEAN NOT NULL DEFAULT TRUE,
  persuasion_level ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
  primary_language VARCHAR(80) NOT NULL DEFAULT 'Espanol latino',
  preferred_phrases TEXT NULL,
  forbidden_phrases TEXT NULL,
  good_examples TEXT NULL,
  bad_examples TEXT NULL,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_personality_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_personality_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_personality_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_business_rules (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(180) NOT NULL,
  description TEXT NULL,
  condition_text TEXT NULL,
  action_text TEXT NULL,
  priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  channel VARCHAR(60) NOT NULL DEFAULT 'all',
  escalation_role VARCHAR(120) NULL,
  effective_until DATE NULL,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_rules_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_rules_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_rules_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_rules_company_status (company_id, status, is_active),
  INDEX idx_ai_rules_company_priority (company_id, priority)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_restrictions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  name VARCHAR(180) NOT NULL,
  restriction_type ENUM('never_disclose','do_not_answer','human_review','sensitive_words','max_quote','max_discount','confidence','schedule') NOT NULL DEFAULT 'human_review',
  description TEXT NULL,
  value_text TEXT NULL,
  channel VARCHAR(60) NOT NULL DEFAULT 'all',
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_restrictions_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_restrictions_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_restrictions_company_status (company_id, status, is_active)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_products (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  item_type ENUM('product','service') NOT NULL DEFAULT 'service',
  name VARCHAR(180) NOT NULL,
  category VARCHAR(120) NULL,
  description TEXT NULL,
  price_type ENUM('fixed','range','quote_required') NOT NULL DEFAULT 'quote_required',
  price_from DECIMAL(14,2) NULL,
  price_to DECIMAL(14,2) NULL,
  currency CHAR(3) NULL,
  delivery_time VARCHAR(160) NULL,
  requirements TEXT NULL,
  stock VARCHAR(120) NULL,
  warranty TEXT NULL,
  restrictions TEXT NULL,
  faqs TEXT NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_by BIGINT UNSIGNED NULL,
  updated_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_products_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_products_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_products_updated_by FOREIGN KEY (updated_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_products_company_status (company_id, status, item_type),
  FULLTEXT idx_ai_products_text (name, description)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_faqs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  question TEXT NOT NULL,
  variants TEXT NULL,
  approved_answer TEXT NOT NULL,
  category VARCHAR(120) NULL,
  tags VARCHAR(255) NULL,
  channel VARCHAR(60) NOT NULL DEFAULT 'all',
  priority ENUM('low','medium','high','critical') NOT NULL DEFAULT 'medium',
  source VARCHAR(160) NULL,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  created_by BIGINT UNSIGNED NULL,
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_faqs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_faqs_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_faqs_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_faqs_company_status (company_id, status, priority),
  FULLTEXT idx_ai_faqs_text (question, variants, approved_answer)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_conversation_examples (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  customer_message TEXT NOT NULL,
  ideal_response TEXT NOT NULL,
  channel VARCHAR(60) NOT NULL DEFAULT 'all',
  category VARCHAR(120) NULL,
  intent VARCHAR(120) NULL,
  tags VARCHAR(255) NULL,
  product_service VARCHAR(180) NULL,
  expected_result VARCHAR(180) NULL,
  status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
  approved_by BIGINT UNSIGNED NULL,
  approved_at TIMESTAMP NULL,
  created_by BIGINT UNSIGNED NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_examples_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_examples_approved_by FOREIGN KEY (approved_by) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_examples_created_by FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_examples_company_status (company_id, status, channel),
  FULLTEXT idx_ai_examples_text (customer_message, ideal_response)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_response_reviews (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  conversation_id BIGINT UNSIGNED NULL,
  message_id BIGINT UNSIGNED NULL,
  customer_message TEXT NULL,
  ai_response TEXT NULL,
  final_response TEXT NULL,
  reviewed_by BIGINT UNSIGNED NULL,
  result ENUM('approved','edited','rejected') NOT NULL DEFAULT 'approved',
  difference_summary TEXT NULL,
  correction_reason TEXT NULL,
  channel VARCHAR(60) NULL,
  intent VARCHAR(120) NULL,
  confidence TINYINT UNSIGNED NULL,
  sources_json JSON NULL,
  reviewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_reviews_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_reviews_conversation FOREIGN KEY (conversation_id) REFERENCES inbox_conversations(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_reviews_message FOREIGN KEY (message_id) REFERENCES inbox_messages(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_reviews_user FOREIGN KEY (reviewed_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_reviews_company_result (company_id, result, reviewed_at),
  INDEX idx_ai_reviews_conversation (company_id, conversation_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_channel_settings (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  channel VARCHAR(60) NOT NULL,
  mode ENUM('manual','assisted','automatic') NOT NULL DEFAULT 'manual',
  min_confidence TINYINT UNSIGNED NOT NULL DEFAULT 75,
  require_approval_for_sensitive BOOLEAN NOT NULL DEFAULT TRUE,
  auto_reply_schedule VARCHAR(180) NULL,
  status ENUM('active','inactive') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_channel_settings_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  UNIQUE KEY uq_ai_channel_settings (company_id, channel),
  INDEX idx_ai_channel_settings_company (company_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_prompt_templates (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  template_key VARCHAR(120) NOT NULL UNIQUE,
  name VARCHAR(180) NOT NULL,
  description TEXT NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_prompt_versions (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  template_id BIGINT UNSIGNED NOT NULL,
  version VARCHAR(40) NOT NULL,
  body MEDIUMTEXT NOT NULL,
  status ENUM('draft','active','archived') NOT NULL DEFAULT 'active',
  author_id BIGINT UNSIGNED NULL,
  change_summary TEXT NULL,
  activated_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_prompt_versions_template FOREIGN KEY (template_id) REFERENCES ai_prompt_templates(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_prompt_versions_author FOREIGN KEY (author_id) REFERENCES users(id) ON DELETE SET NULL,
  UNIQUE KEY uq_ai_prompt_version (template_id, version),
  INDEX idx_ai_prompt_versions_status (template_id, status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
