CREATE TABLE IF NOT EXISTS ai_knowledge_sources (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  document_id BIGINT UNSIGNED NULL,
  source_type ENUM('document','url','text','faq','example','manual') NOT NULL DEFAULT 'document',
  name VARCHAR(220) NOT NULL,
  category VARCHAR(120) NULL,
  tags VARCHAR(255) NULL,
  mime_type VARCHAR(120) NULL,
  file_size BIGINT UNSIGNED NULL,
  source_url VARCHAR(500) NULL,
  version INT UNSIGNED NOT NULL DEFAULT 1,
  status ENUM('pending','processing','ready','failed','inactive') NOT NULL DEFAULT 'pending',
  extracted_text MEDIUMTEXT NULL,
  summary TEXT NULL,
  error_message TEXT NULL,
  uploaded_by BIGINT UNSIGNED NULL,
  expires_at DATE NULL,
  processed_at TIMESTAMP NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_sources_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_sources_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_sources_user FOREIGN KEY (uploaded_by) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_sources_company_status (company_id, status, source_type),
  INDEX idx_ai_sources_document (company_id, document_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_knowledge_chunks (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  source_id BIGINT UNSIGNED NOT NULL,
  document_id BIGINT UNSIGNED NULL,
  chunk_index INT UNSIGNED NOT NULL DEFAULT 0,
  title VARCHAR(240) NOT NULL,
  content MEDIUMTEXT NOT NULL,
  content_hash CHAR(64) NOT NULL,
  token_estimate INT UNSIGNED NOT NULL DEFAULT 0,
  retrieval_weight DECIMAL(6,3) NOT NULL DEFAULT 1,
  embedding_provider VARCHAR(80) NOT NULL DEFAULT 'text-index-v1',
  embedding_ref VARCHAR(180) NULL,
  status ENUM('ready','inactive') NOT NULL DEFAULT 'ready',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_chunks_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_chunks_source FOREIGN KEY (source_id) REFERENCES ai_knowledge_sources(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_chunks_document FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL,
  UNIQUE KEY uq_ai_chunk_hash (company_id, source_id, content_hash),
  INDEX idx_ai_chunks_company_status (company_id, status),
  FULLTEXT idx_ai_chunks_text (title, content)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_context_logs (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  module VARCHAR(80) NOT NULL,
  query_text TEXT NULL,
  context_summary TEXT NULL,
  sources_json JSON NULL,
  token_estimate INT UNSIGNED NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_context_logs_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_context_logs_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  INDEX idx_ai_context_logs_company_module (company_id, module, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_generated_responses (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  company_id BIGINT UNSIGNED NOT NULL,
  user_id BIGINT UNSIGNED NULL,
  context_log_id BIGINT UNSIGNED NULL,
  module VARCHAR(80) NOT NULL,
  channel VARCHAR(60) NULL,
  customer_message TEXT NULL,
  generated_response TEXT NOT NULL,
  confidence TINYINT UNSIGNED NULL,
  sources_json JSON NULL,
  status ENUM('draft','approved','edited','rejected','sent') NOT NULL DEFAULT 'draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_ai_generated_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
  CONSTRAINT fk_ai_generated_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL,
  CONSTRAINT fk_ai_generated_context FOREIGN KEY (context_log_id) REFERENCES ai_context_logs(id) ON DELETE SET NULL,
  INDEX idx_ai_generated_company_status (company_id, status, created_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
