CREATE TABLE IF NOT EXISTS ai_brand_profiles (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    brand_route_id BIGINT UNSIGNED NOT NULL,
    status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
    company_name VARCHAR(180) NULL,
    description TEXT NULL,
    industry VARCHAR(160) NULL,
    main_offering TEXT NULL,
    customer_type TEXT NULL,
    value_proposition TEXT NULL,
    differentiators TEXT NULL,
    business_hours VARCHAR(220) NULL,
    locations TEXT NULL,
    website VARCHAR(220) NULL,
    contact_details TEXT NULL,
    primary_objective VARCHAR(220) NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    published_at TIMESTAMP NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ai_brand_profiles_scope (company_id, brand_route_id),
    INDEX idx_ai_brand_profiles_status (company_id, status),
    CONSTRAINT fk_ai_brand_profiles_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_brand_profiles_route FOREIGN KEY (brand_route_id) REFERENCES ai_brand_routes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_brand_personalities (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    brand_route_id BIGINT UNSIGNED NOT NULL,
    status ENUM('draft','review','published','archived') NOT NULL DEFAULT 'draft',
    tone ENUM('formal','professional','close','technical','commercial') NOT NULL DEFAULT 'professional',
    allow_emojis BOOLEAN NOT NULL DEFAULT FALSE,
    response_length ENUM('short','medium','detailed') NOT NULL DEFAULT 'medium',
    greeting_style VARCHAR(180) NULL,
    closing_style VARCHAR(180) NULL,
    use_customer_name BOOLEAN NOT NULL DEFAULT TRUE,
    persuasion_level ENUM('low','medium','high') NOT NULL DEFAULT 'medium',
    primary_language VARCHAR(80) NOT NULL DEFAULT 'Espanol latino',
    preferred_phrases TEXT NULL,
    forbidden_phrases TEXT NULL,
    good_examples TEXT NULL,
    bad_examples TEXT NULL,
    created_by BIGINT UNSIGNED NULL,
    updated_by BIGINT UNSIGNED NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ai_brand_personalities_scope (company_id, brand_route_id),
    INDEX idx_ai_brand_personalities_status (company_id, status),
    CONSTRAINT fk_ai_brand_personalities_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_brand_personalities_route FOREIGN KEY (brand_route_id) REFERENCES ai_brand_routes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ai_training_brand_scopes (
    id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    company_id BIGINT UNSIGNED NOT NULL,
    brand_route_id BIGINT UNSIGNED NOT NULL,
    entity_type ENUM('product','rule','faq','example','document','review') NOT NULL,
    entity_id BIGINT UNSIGNED NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE KEY uq_ai_training_brand_scope (company_id, brand_route_id, entity_type, entity_id),
    INDEX idx_ai_training_brand_scope_entity (company_id, entity_type, entity_id),
    CONSTRAINT fk_ai_training_brand_scopes_company FOREIGN KEY (company_id) REFERENCES companies(id) ON DELETE CASCADE,
    CONSTRAINT fk_ai_training_brand_scopes_route FOREIGN KEY (brand_route_id) REFERENCES ai_brand_routes(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
